{% set name = "riskparityportfolio" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/riskparityportfolio-{{ version }}.tar.gz
  sha256: 66ae0fc161b181991dec828ee0a84820be2b36e1926393294ad6b61d093a7741
  patches:
    - patches/0001-Ignore-the-vendored-eigen3.patch

build:
  skip: true  # [win]
  script:
    # Do not use the vendored sources of eigen.
    - rm -Rf third_party
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11 >=2.4
    - numpy
    - jaxlib
    - jax
    - quadprog
    - tqdm
    - pip
    - eigen
  run:
    - python
    - pybind11 >=2.4
    - jaxlib
    - jax
    - quadprog
    - tqdm

test:
  imports:
    - riskparityportfolio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dppalomar/riskparity.py
  summary: Blazingly fast design of risk parity portfolios
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jjerphan
